{
  description = "My personal NUR repository";
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";

    flake-parts.url = "github:hercules-ci/flake-parts";
    dream2nix = {
      url = "github:nix-community/dream2nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    pkgs-by-name-for-flake-parts.url = "github:drupol/pkgs-by-name-for-flake-parts";

    pyproject-nix = {
      url = "github:pyproject-nix/pyproject.nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    uv2nix = {
      url = "github:pyproject-nix/uv2nix";
      inputs.pyproject-nix.follows = "pyproject-nix";
      inputs.nixpkgs.follows = "nixpkgs";
    };
    pyproject-build-systems = {
      url = "github:pyproject-nix/build-system-pkgs";
      inputs = {
        pyproject-nix.follows = "pyproject-nix";
        uv2nix.follows = "uv2nix";
        nixpkgs.follows = "nixpkgs";
      };
    };
    dify-src = {
      url = "github:langgenius/dify/1.13.1";
      flake = false;
    };

  };
  outputs =
    {
      self,
      nixpkgs,
      flake-parts,
      dream2nix,
      pkgs-by-name-for-flake-parts,
      uv2nix,
      pyproject-nix,
      pyproject-build-systems,
      dify-src,
      ...
    }@inputs:
    flake-parts.lib.mkFlake { inherit inputs; } (
      { inputs, ... }:
      let
        # Load the Dify workspace (system-independent, only parses pyproject.toml + uv.lock)
        difyWorkspace = uv2nix.lib.workspace.loadWorkspace {
          workspaceRoot = "${dify-src}/api";
        };
      in
      {

        # Note: Not importing pkgs-by-name-for-flake-parts to avoid automatic discovery of incompatible packages
        # imports = [
        #   inputs.pkgs-by-name-for-flake-parts.flakeModule
        # ];
        systems = [
          "x86_64-linux"
          "aarch64-linux"
          "aarch64-darwin"
          "x86_64-darwin"
        ];

        perSystem =
          {
            lib,
            system,
            ...
          }:
          let
            # Own nixpkgs instance so unfree packages (unity-cli, feishu-lark,
            # falcon-sensor, ...) evaluate with plain `nix build .#<name>`.
            # garnix CI is include-list based, so this does not add CI builds.
            pkgs = import nixpkgs {
              inherit system;
              config.allowUnfree = true;
            };
            isLinuxSystem = lib.hasSuffix "linux" system;

            # Overrides for sdist packages missing build system declarations
            difyPyprojectOverrides =
              final: prev:
              let
                addSetuptools =
                  name:
                  prev.${name}.overrideAttrs (old: {
                    nativeBuildInputs = (old.nativeBuildInputs or [ ]) ++ [
                      (final.resolveBuildSystem { setuptools = [ ]; })
                    ];
                  });

                # All sdist-only packages in Dify's uv.lock that lack build-system metadata
                # Generated by parsing uv.lock for packages without aarch64 wheels
                setuptools-packages = [
                  "alibabacloud-credentials-api"
                  "alibabacloud-endpoint-util"
                  "alibabacloud-gateway-spi"
                  "alibabacloud-openapi-util"
                  "alibabacloud-oss-sdk"
                  "alibabacloud-oss-util"
                  "alibabacloud-tea"
                  "alibabacloud-tea-fileform"
                  "alibabacloud-tea-xml"
                  "aliyun-log-python-sdk"
                  "aliyun-python-sdk-core"
                  "crcmod"
                  "esdk-obs-python"
                  "intervaltree"
                  "jieba"
                  "langdetect"
                  "odfpy"
                  "oss2"
                  "psycogreen"
                  "pypika"
                  "tcvdb-text"
                  "tos"
                ];
              in
              lib.genAttrs setuptools-packages addSetuptools
              // {
                # mysql-connector-python wheel bundles vendor libs missing system deps
                mysql-connector-python = prev.mysql-connector-python.overrideAttrs (old: {
                  buildInputs = (old.buildInputs or [ ]) ++ [
                    pkgs.libkrb5
                    pkgs.systemdLibs
                    pkgs.libxcrypt-legacy
                  ];
                });
              };

            # Build the Dify Python environment (only on Linux)
            difyPythonSet = lib.optionalAttrs isLinuxSystem (
              (pkgs.callPackage pyproject-nix.build.packages {
                python = pkgs.python312;
              }).overrideScope
                (
                  lib.composeManyExtensions [
                    pyproject-build-systems.overlays.default
                    (difyWorkspace.mkPyprojectOverlay { sourcePreference = "wheel"; })
                    difyPyprojectOverrides
                  ]
                )
            );

            difyApiEnv = lib.optionalAttrs isLinuxSystem (
              (difyPythonSet.mkVirtualEnv "dify-api-env" difyWorkspace.deps.default).overrideAttrs {
                # typer and typer-slim both provide typer/* files
                venvIgnoreCollisions = [ "lib/python3.12/site-packages/typer/*" ];
              }
            );

            difyPackages = lib.optionalAttrs isLinuxSystem {
              dify-api = pkgs.callPackage ./pkgs/dify/api/package.nix {
                inherit difyApiEnv;
                inherit dify-src;
              };
              dify-web = pkgs.callPackage ./pkgs/dify/web/package.nix { };
            };
          in
          {
            # pkgsDirectory = ./pkgs;
            # pkgsNameSeparator = "-";
            packages =
              let
                # default.nix already discovers everything under pkgs/ through
                # pkgs/manifest.nix and drops what meta.platforms excludes, so
                # there is no second list to maintain here.
                #
                # This used to re-walk pkgs/ itself, wrapping each import in
                # builtins.tryEval and silently dropping whatever failed. That
                # hid real breakage: mcporter had been unbuildable since
                # nixpkgs removed pnpm fetcherVersion 2, and simply vanished
                # from the flake outputs instead of failing.
                allPackages = import ./. {
                  inherit self lib pkgs;
                };

                combinedPackages = allPackages // difyPackages;
              in
              combinedPackages
              // {
                default = combinedPackages.librime or combinedPackages.default or null;
              };

            apps = {
              update = {
                type = "app";
                # writeShellApplication records meta.mainProgram, so getExe
                # gives the binary path directly — the old form interpolated
                # the store path and then ran builtins.toString over the
                # resulting string, both of which were no-ops.
                program = lib.getExe (
                  pkgs.writeShellApplication {
                    name = "update";
                    runtimeInputs = with pkgs; [
                      bash
                      coreutils
                      git
                      gnused
                      jq
                      nix
                      nvfetcher
                      perl
                      ripgrep
                    ];
                    text = ''
                      repo_root="$(git rev-parse --show-toplevel 2>/dev/null || pwd)"
                      cd "$repo_root"
                      bash ./scripts/update.sh
                    '';
                  }
                );
              };
            };
            devShells.default = pkgs.mkShell {
              buildInputs = with pkgs; [
                nixfmt-rfc-style
                nixd
                statix
              ];
            };
          };

        flake = {
          # Overlay that provides all NUR packages
          # Uses lazy evaluation and super (prev) to avoid infinite recursion
          overlays.default = import ./overlay.nix;

          nixosModules = import ./modules;
          homeModules = import ./modules/home.nix;
          templates = import ./templates;
        };
      }
    );
}
