[tool.poetry]
name = "nixopsenv"
version = "2.0.0"
description = "NixOps 2.0"
authors = ["Adam Hoese <adam.hose@tweag.io>"]

[tool.poetry.dependencies]
python = "^3.10"
nixops-aws = { git = "https://github.com/xiongchenyu6/nixops-aws.git",branch = "remove-hvm-option" }
nixops-gcp = {git = "https://github.com/xiongchenyu6/nixops-gce.git"}
nixops-hetznercloud = {git = "https://github.com/xiongchenyu6/nixops-hetznercloud.git"}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
