# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  cc-gateway = {
    pname = "cc-gateway";
    version = "447fad19b2b98602058951cad53895ed56e5ea84";
    src = fetchgit {
      url = "https://github.com/motiful/cc-gateway.git";
      rev = "447fad19b2b98602058951cad53895ed56e5ea84";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-GUss0AKl/VocbuchGZinaWY/pgsM7B5ZnYlk3j/Wql0=";
    };
    date = "2026-04-02";
  };
  combobulate = {
    pname = "combobulate";
    version = "a4efc0e8ce7f4aead027fe98f70dcc0a659b8cbf";
    src = fetchgit {
      url = "https://github.com/mickeynp/combobulate.git";
      rev = "a4efc0e8ce7f4aead027fe98f70dcc0a659b8cbf";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-i+inK8Qb5J8+lTNfF2KukIW9OUnsGrnqn8IHyZeMK7c=";
    };
    date = "2026-04-20";
  };
  copilot-el = {
    pname = "copilot-el";
    version = "ab5c58bc969f52f6d75e972658f2c3381c70b4fa";
    src = fetchgit {
      url = "https://github.com/zerolfx/copilot.el.git";
      rev = "ab5c58bc969f52f6d75e972658f2c3381c70b4fa";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-hXZsu/pDE0/Li+GcFbC9ObbY4N1sVWDZ48CJfDrJmL4=";
    };
    date = "2026-03-31";
  };
  gotron-sdk = {
    pname = "gotron-sdk";
    version = "v0.26.0";
    src = fetchFromGitHub {
      owner = "fbsobreira";
      repo = "gotron-sdk";
      rev = "v0.26.0";
      fetchSubmodules = false;
      sha256 = "sha256-GqMXqUnvOt92xVcURFQa+uqTqU7LZd8vFEh78ZlTp+k=";
    };
  };
  gptel = {
    pname = "gptel";
    version = "71b9f9414536c4cd35d8c02d3c8ad4fc4aea8718";
    src = fetchgit {
      url = "https://github.com/karthink/gptel.git";
      rev = "71b9f9414536c4cd35d8c02d3c8ad4fc4aea8718";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-VHRRHgBkC3ieepbL6wM+L1rTz9UPfQji2DFsGEOzXyk=";
    };
    date = "2026-04-27";
  };
  hashtopolis-agent = {
    pname = "hashtopolis-agent";
    version = "v0.7.4";
    src = fetchFromGitHub {
      owner = "hashtopolis";
      repo = "agent-python";
      rev = "v0.7.4";
      fetchSubmodules = false;
      sha256 = "sha256-KyuDXE+B/Rq4N1noJvgNBif9po7b6p6SXco1yBoZWXw=";
    };
  };
  hashtopolis-server = {
    pname = "hashtopolis-server";
    version = "v1.0.0-rainbow6";
    src = fetchFromGitHub {
      owner = "hashtopolis";
      repo = "server";
      rev = "v1.0.0-rainbow6";
      fetchSubmodules = false;
      sha256 = "sha256-XNdbxKLw3DUNEUkAQMh6ysEnjC2gsvnHgc5L59Ke/y8=";
    };
  };
  helmify = {
    pname = "helmify";
    version = "v0.4.19";
    src = fetchFromGitHub {
      owner = "arttor";
      repo = "helmify";
      rev = "v0.4.19";
      fetchSubmodules = false;
      sha256 = "sha256-casZJRHpTbakI1FdSYPYcda2G8xPP+feTQil6R+FdbE=";
    };
  };
  korb = {
    pname = "korb";
    version = "v2.3.4";
    src = fetchFromGitHub {
      owner = "BeryJu";
      repo = "korb";
      rev = "v2.3.4";
      fetchSubmodules = false;
      sha256 = "sha256-jznXK+YlPjglafrTA1jlCuxKkZSetgk9GeY0FWxnHy4=";
    };
  };
  librime-lua = {
    pname = "librime-lua";
    version = "ef17b1f5e0c3f430d6039309d8ebd27bb26bc671";
    src = fetchgit {
      url = "https://github.com/hchunhui/librime-lua.git";
      rev = "ef17b1f5e0c3f430d6039309d8ebd27bb26bc671";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-kuNvJUiAlt+78U5ZqRbets2M/mrsVaECYxVFZRW/R40=";
    };
    date = "2026-04-26";
  };
  magit-gitflow = {
    pname = "magit-gitflow";
    version = "cc41b561ec6eea947fe9a176349fb4f771ed865b";
    src = fetchgit {
      url = "https://github.com/jtatarik/magit-gitflow.git";
      rev = "cc41b561ec6eea947fe9a176349fb4f771ed865b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-LqBvn+Ev8GsZG6zmQ5eGt+5vDQk5ywqvagrvnzNP5ks=";
    };
    date = "2017-09-29";
  };
  magit-town = {
    pname = "magit-town";
    version = "4ce962e6e2d8249d3a5aa4c40e9924a424b50ebf";
    src = fetchgit {
      url = "https://github.com/natecox/magit-town.git";
      rev = "4ce962e6e2d8249d3a5aa4c40e9924a424b50ebf";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-dcLarzN9miAxzW9IP3IECxjRuShR/D3m5eU7vV6YE+A=";
    };
    date = "2019-04-02";
  };
  my2sql = {
    pname = "my2sql";
    version = "69b39554cb116d02fba389ff258ca9736dea7437";
    src = fetchurl {
      url = "https://github.com/liuhr/my2sql/raw/master/releases/centOS_release_7.x/my2sql";
      sha256 = "sha256-ggsA5U6AgszBuwAipX8BSuQSA0o67GDnkTZNkHhPpfo=";
    };
    date = "2026-04-23";
  };
  openagent-darwin-arm64 = {
    pname = "openagent-darwin-arm64";
    version = "v1.785.0";
    src = fetchurl {
      url = "https://github.com/the-open-agent/openagent/releases/download/v1.785.0/openagent_Darwin_arm64.tar.gz";
      sha256 = "sha256-DVIq8ATMM51hEV2gLCQjihlLAZ2fU4ZHJtjJJNxqvbg=";
    };
  };
  openagent-darwin-x86_64 = {
    pname = "openagent-darwin-x86_64";
    version = "v1.785.0";
    src = fetchurl {
      url = "https://github.com/the-open-agent/openagent/releases/download/v1.785.0/openagent_Darwin_x86_64.tar.gz";
      sha256 = "sha256-cKB88sKhG2C54C/Zd5Iwrv8okLj9s9zlB+SeBjVsU/M=";
    };
  };
  openagent-linux-arm64 = {
    pname = "openagent-linux-arm64";
    version = "v1.785.0";
    src = fetchurl {
      url = "https://github.com/the-open-agent/openagent/releases/download/v1.785.0/openagent_Linux_arm64.tar.gz";
      sha256 = "sha256-oxa9xuEaX+ChQdybccMBzVz/bMBTCntOq6PHWNyrxgk=";
    };
  };
  openagent-linux-x86_64 = {
    pname = "openagent-linux-x86_64";
    version = "v1.785.0";
    src = fetchurl {
      url = "https://github.com/the-open-agent/openagent/releases/download/v1.785.0/openagent_Linux_x86_64.tar.gz";
      sha256 = "sha256-inyzuz+015+ynVA4agZ8Z7zue4hmnnqXTNpYaVcsyJg=";
    };
  };
  org-cv = {
    pname = "org-cv";
    version = "e8de952df7669b38ca475d00fe943ab96d8cfac4";
    src = fetchgit {
      url = "https://gitlab.com/Titan-C/org-cv.git";
      rev = "e8de952df7669b38ca475d00fe943ab96d8cfac4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-qwJTtyfNZpA4YCOxh90hXW89aYThE9K6GnJIxeUI7No=";
    };
    date = "2025-01-24";
  };
  sub2api = {
    pname = "sub2api";
    version = "v0.1.121";
    src = fetchFromGitHub {
      owner = "Wei-Shaw";
      repo = "sub2api";
      rev = "v0.1.121";
      fetchSubmodules = false;
      sha256 = "sha256-OEkD91U2RiWvXhSSL3fqpDr0a0JsiffvmsL2NSbwjnU=";
    };
  };
  sui = {
    pname = "sui";
    version = "testnet-v1.71.0";
    src = fetchurl {
      url = "https://github.com/MystenLabs/sui/releases/download/testnet-v1.71.0/sui-testnet-v1.71.0-ubuntu-x86_64.tgz";
      sha256 = "sha256-aYFa16PHYZQhJqrv25pHVJxehv4+Do/gcYynAPRWZv0=";
    };
  };
  supabase-realtime = {
    pname = "supabase-realtime";
    version = "v2.89.0";
    src = fetchFromGitHub {
      owner = "supabase";
      repo = "realtime";
      rev = "v2.89.0";
      fetchSubmodules = false;
      sha256 = "sha256-8RfBmWaQIUG8z34/sbkaAEl4l4ysUXqbqRbz6NTR9Fc=";
    };
  };
  xiaohongshu-mcp = {
    pname = "xiaohongshu-mcp";
    version = "v2026.04.17.0444-c63748f";
    src = fetchFromGitHub {
      owner = "xpzouying";
      repo = "xiaohongshu-mcp";
      rev = "v2026.04.17.0444-c63748f";
      fetchSubmodules = false;
      sha256 = "sha256-s5yPNDNW30CVcZ1yuxJUsPb2ONiy4kFzpvo1zubjQ8A=";
    };
  };
}
