# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  alias-tips = {
    pname = "alias-tips";
    version = "cd13ef223c4f310d774cdf8cb0435474cc2bcbbe";
    src = fetchgit {
      url = "https://github.com/djui/alias-tips.git";
      rev = "cd13ef223c4f310d774cdf8cb0435474cc2bcbbe";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-fDYAJSJHatxHhAT68AH4PuIHdwxFXipAoDHITVpkkkE=";
    };
  };
  bttc = {
    pname = "bttc";
    version = "v1.0.2";
    src = fetchFromGitHub ({
      owner = "bttcprotocol";
      repo = "bttc";
      rev = "v1.0.2";
      fetchSubmodules = true;
      sha256 = "sha256-qptNGs6NmbIEzmosASAvdZSIUhw5RVcgEF55/RhgR3I=";
    });
  };
  copilot = {
    pname = "copilot";
    version = "3b78e9b6fd7b7e78180a795affdfbbe89af2ccec";
    src = fetchgit {
      url = "https://github.com/zerolfx/copilot.el.git";
      rev = "3b78e9b6fd7b7e78180a795affdfbbe89af2ccec";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-x4o6TJfa32DN6Eb+t+9e6iQ+byK4KA06qijMUgUMsZg=";
    };
  };
  delivery = {
    pname = "delivery";
    version = "v1.0.2";
    src = fetchFromGitHub ({
      owner = "bttcprotocol";
      repo = "delivery";
      rev = "v1.0.2";
      fetchSubmodules = true;
      sha256 = "sha256-HItF37qlIm6IT8WSomTulkX7524UZwpwMbqyjckXFxA=";
    });
  };
  epc = {
    pname = "epc";
    version = "0.0.5";
    src = fetchurl {
      url = "https://pypi.io/packages/source/e/epc/epc-0.0.5.tar.gz";
      sha256 = "sha256-oU0up0gXlVog6wCBLjpGMKEyiX602XZCAkDxFSwNfSU=";
    };
  };
  launch = {
    pname = "launch";
    version = "f71388e3a8091a1c6bc10aa03d7edf8e7b638f23";
    src = fetchgit {
      url = "https://github.com/bttcprotocol/launch.git";
      rev = "f71388e3a8091a1c6bc10aa03d7edf8e7b638f23";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-5iUjWxjTmMxkfo+WZnjCKmHNTeaKkv5jdiDawMmvbQw=";
    };
  };
  ligature = {
    pname = "ligature";
    version = "5eb950ada991705fdda4456970b0321241ee2bfa";
    src = fetchgit {
      url = "https://github.com/mickeynp/ligature.el.git";
      rev = "5eb950ada991705fdda4456970b0321241ee2bfa";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-o6iL4mwTzfD7JOlWP4Mv27+nRGplcseGjam7WIlHZTc=";
    };
  };
  lsp-bridge = {
    pname = "lsp-bridge";
    version = "3c1751785154050c488dd6115c41a335dff3ef06";
    src = fetchgit {
      url = "https://github.com/manateelazycat/lsp-bridge.git";
      rev = "3c1751785154050c488dd6115c41a335dff3ef06";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-EUSPjHMjfNXmurkIEvgo/aQgDG1oTHFNY81lC6bggTo=";
    };
  };
  my_cookies = {
    pname = "my_cookies";
    version = "0.1.3";
    src = fetchurl {
      url = "https://pypi.io/packages/source/m/my_cookies/my_cookies-0.1.3.tar.gz";
      sha256 = "sha256-3e5j0HFOXUyUo6YVUKQnbaxvAUtDoRTzGqW8HUfzrQ8=";
    };
  };
  oci-arm-host-capacity = {
    pname = "oci-arm-host-capacity";
    version = "f0ad2cea022423f687ff3b65fd64b55e59848e17";
    src = fetchgit {
      url = "https://github.com/hitrov/oci-arm-host-capacity.git";
      rev = "f0ad2cea022423f687ff3b65fd64b55e59848e17";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-dTiv2WPS4UCmR5XlfwdRAQJ/Mq237i/H/Teu68FB23E=";
    };
  };
  org-cv = {
    pname = "org-cv";
    version = "332c72880df2ed8f25d3693907cedfe53b07f49e";
    src = fetchgit {
      url = "https://gitlab.com/Titan-C/org-cv.git";
      rev = "332c72880df2ed8f25d3693907cedfe53b07f49e";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-AtCjoezjQecqIbHelxSAupqA0AdXKSLR/30TshcSt6s=";
    };
  };
  wakatime-zsh-plugin = {
    pname = "wakatime-zsh-plugin";
    version = "69c6028b0c8f72e2afcfa5135b1af29afb49764a";
    src = fetchgit {
      url = "https://github.com/sobolevn/wakatime-zsh-plugin.git";
      rev = "69c6028b0c8f72e2afcfa5135b1af29afb49764a";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sha256 = "sha256-pA1VOkzbHQjmcI2skzB/OP5pXn8CFUz5Ok/GLC6KKXQ=";
    };
  };
}
