# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchgit,
  fetchurl,
  fetchFromGitHub,
  dockerTools,
}:
{
  casibase-darwin-arm64 = {
    pname = "casibase-darwin-arm64";
    version = "v1.764.0";
    src = fetchurl {
      url = "https://github.com/casibase/casibase/releases/download/v1.764.0/casibase_Darwin_arm64.tar.gz";
      sha256 = "sha256-PATtqZBrwsXDpT49MWlL5AAHuywuak2ocEGEknRx/IE=";
    };
  };
  casibase-darwin-x86_64 = {
    pname = "casibase-darwin-x86_64";
    version = "v1.764.0";
    src = fetchurl {
      url = "https://github.com/casibase/casibase/releases/download/v1.764.0/casibase_Darwin_x86_64.tar.gz";
      sha256 = "sha256-E1hUORXqUcbRZxyljUmX0f4F0e7hCYb+qkrP/tJjSjc=";
    };
  };
  casibase-linux-arm64 = {
    pname = "casibase-linux-arm64";
    version = "v1.764.0";
    src = fetchurl {
      url = "https://github.com/casibase/casibase/releases/download/v1.764.0/casibase_Linux_arm64.tar.gz";
      sha256 = "sha256-8b3Etm/RxQXuArIdFjJD4orZ7vu+rAewvlTXg9H6Dkw=";
    };
  };
  casibase-linux-x86_64 = {
    pname = "casibase-linux-x86_64";
    version = "v1.764.0";
    src = fetchurl {
      url = "https://github.com/casibase/casibase/releases/download/v1.764.0/casibase_Linux_x86_64.tar.gz";
      sha256 = "sha256-obEIzdGZ+25r5TRIw40BykB07K/KpeRAQUPqalD5mBw=";
    };
  };
  cc-gateway = {
    pname = "cc-gateway";
    version = "447fad19b2b98602058951cad53895ed56e5ea84";
    src = fetchgit {
      url = "https://github.com/motiful/cc-gateway.git";
      rev = "447fad19b2b98602058951cad53895ed56e5ea84";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-GUss0AKl/VocbuchGZinaWY/pgsM7B5ZnYlk3j/Wql0=";
    };
    date = "2026-04-02";
  };
  combobulate = {
    pname = "combobulate";
    version = "74fc764c58904f6f7a9ab3417887f0eaa44af30b";
    src = fetchgit {
      url = "https://github.com/mickeynp/combobulate.git";
      rev = "74fc764c58904f6f7a9ab3417887f0eaa44af30b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-VlXofftxEz21ew7C1Dv+9dW7xCU1G8p3E8wN7qzgYME=";
    };
    date = "2026-04-10";
  };
  copilot-el = {
    pname = "copilot-el";
    version = "ab5c58bc969f52f6d75e972658f2c3381c70b4fa";
    src = fetchgit {
      url = "https://github.com/zerolfx/copilot.el.git";
      rev = "ab5c58bc969f52f6d75e972658f2c3381c70b4fa";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-hXZsu/pDE0/Li+GcFbC9ObbY4N1sVWDZ48CJfDrJmL4=";
    };
    date = "2026-03-31";
  };
  gotron-sdk = {
    pname = "gotron-sdk";
    version = "v0.26.0";
    src = fetchFromGitHub {
      owner = "fbsobreira";
      repo = "gotron-sdk";
      rev = "v0.26.0";
      fetchSubmodules = false;
      sha256 = "sha256-GqMXqUnvOt92xVcURFQa+uqTqU7LZd8vFEh78ZlTp+k=";
    };
  };
  gptel = {
    pname = "gptel";
    version = "8d6411b5f89d796c817ff79324973b8910e164fe";
    src = fetchgit {
      url = "https://github.com/karthink/gptel.git";
      rev = "8d6411b5f89d796c817ff79324973b8910e164fe";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-BgOtog94HH/SRV1NRxv3tOu7rhxVXN0UZAhinG7DhX4=";
    };
    date = "2026-04-10";
  };
  hashtopolis-agent = {
    pname = "hashtopolis-agent";
    version = "v0.7.4";
    src = fetchFromGitHub {
      owner = "hashtopolis";
      repo = "agent-python";
      rev = "v0.7.4";
      fetchSubmodules = false;
      sha256 = "sha256-KyuDXE+B/Rq4N1noJvgNBif9po7b6p6SXco1yBoZWXw=";
    };
  };
  hashtopolis-server = {
    pname = "hashtopolis-server";
    version = "v1.0.0-rainbow5";
    src = fetchFromGitHub {
      owner = "hashtopolis";
      repo = "server";
      rev = "v1.0.0-rainbow5";
      fetchSubmodules = false;
      sha256 = "sha256-ezfd3BT+iEPu42gQfAb/zQ5E0jbmxmtQCRD6T6S6oXY=";
    };
  };
  helmify = {
    pname = "helmify";
    version = "v0.4.19";
    src = fetchFromGitHub {
      owner = "arttor";
      repo = "helmify";
      rev = "v0.4.19";
      fetchSubmodules = false;
      sha256 = "sha256-casZJRHpTbakI1FdSYPYcda2G8xPP+feTQil6R+FdbE=";
    };
  };
  korb = {
    pname = "korb";
    version = "v2.3.4";
    src = fetchFromGitHub {
      owner = "BeryJu";
      repo = "korb";
      rev = "v2.3.4";
      fetchSubmodules = false;
      sha256 = "sha256-jznXK+YlPjglafrTA1jlCuxKkZSetgk9GeY0FWxnHy4=";
    };
  };
  librime-lua = {
    pname = "librime-lua";
    version = "68f9c364a2d25a04c7d4794981d7c796b05ab627";
    src = fetchgit {
      url = "https://github.com/hchunhui/librime-lua.git";
      rev = "68f9c364a2d25a04c7d4794981d7c796b05ab627";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-m7/qXdIlMMHscDDcFmusNuOR0cuzPpDQdprqRci8qZw=";
    };
    date = "2025-07-07";
  };
  magit-gitflow = {
    pname = "magit-gitflow";
    version = "cc41b561ec6eea947fe9a176349fb4f771ed865b";
    src = fetchgit {
      url = "https://github.com/jtatarik/magit-gitflow.git";
      rev = "cc41b561ec6eea947fe9a176349fb4f771ed865b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-LqBvn+Ev8GsZG6zmQ5eGt+5vDQk5ywqvagrvnzNP5ks=";
    };
    date = "2017-09-29";
  };
  magit-town = {
    pname = "magit-town";
    version = "4ce962e6e2d8249d3a5aa4c40e9924a424b50ebf";
    src = fetchgit {
      url = "https://github.com/natecox/magit-town.git";
      rev = "4ce962e6e2d8249d3a5aa4c40e9924a424b50ebf";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-dcLarzN9miAxzW9IP3IECxjRuShR/D3m5eU7vV6YE+A=";
    };
    date = "2019-04-02";
  };
  my2sql = {
    pname = "my2sql";
    version = "71a069af44554b7e6367b2cb9735c06ab5353fe4";
    src = fetchurl {
      url = "https://github.com/liuhr/my2sql/raw/master/releases/centOS_release_7.x/my2sql";
      sha256 = "sha256-ggsA5U6AgszBuwAipX8BSuQSA0o67GDnkTZNkHhPpfo=";
    };
    date = "2026-01-06";
  };
  org-cv = {
    pname = "org-cv";
    version = "e8de952df7669b38ca475d00fe943ab96d8cfac4";
    src = fetchgit {
      url = "https://gitlab.com/Titan-C/org-cv.git";
      rev = "e8de952df7669b38ca475d00fe943ab96d8cfac4";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-qwJTtyfNZpA4YCOxh90hXW89aYThE9K6GnJIxeUI7No=";
    };
    date = "2025-01-24";
  };
  sub2api = {
    pname = "sub2api";
    version = "v0.1.110";
    src = fetchFromGitHub {
      owner = "Wei-Shaw";
      repo = "sub2api";
      rev = "v0.1.110";
      fetchSubmodules = false;
      sha256 = "sha256-uvezACyazy9ol/oxx273hG3uNcKegKr/9KrX+ZPa0fo=";
    };
  };
  sui = {
    pname = "sui";
    version = "mainnet-v1.69.2";
    src = fetchurl {
      url = "https://github.com/MystenLabs/sui/releases/download/mainnet-v1.69.2/sui-mainnet-v1.69.2-ubuntu-x86_64.tgz";
      sha256 = "sha256-c2E5eqk/ISuv9fgrouOYRHR6kBmheHPJKM81meObbH0=";
    };
  };
  xiaohongshu-mcp = {
    pname = "xiaohongshu-mcp";
    version = "v2026.04.09.1645-7732044";
    src = fetchFromGitHub {
      owner = "xpzouying";
      repo = "xiaohongshu-mcp";
      rev = "v2026.04.09.1645-7732044";
      fetchSubmodules = false;
      sha256 = "sha256-sm0maJypWFRq4jsmE9vVlLZrs4HJpJWY+aA3YFAuF8I=";
    };
  };
}
